package com.example.sayvis.model

/**
 * Risk classification for Zero Trust Action Model.
 */
enum class RiskLevel(val labelEn: String, val labelFa: String, val colorHex: Long) {
    LOW_RISK("Low Risk", "کم‌خطر", 0xFF10B981), // Green
    MEDIUM_RISK("Medium Risk", "خطر متوسط", 0xFFF59E0B), // Amber
    HIGHER_RISK("High Risk", "پرخطر", 0xFFEF4444), // Red
    CRITICAL("Critical", "بحرانی", 0xFF991B1B) // Deep Crimson
}

/**
 * Lifecycle status of an AWARE proactive opportunity.
 */
enum class OpportunityStatus(val labelEn: String, val labelFa: String) {
    PENDING("Pending Evaluation", "در انتظار بررسی"),
    APPROVED("Approved by Owner", "تأییدشده توسط مالک"),
    EXECUTED("Executed", "اجراشده"),
    DISMISSED("Dismissed", "ردشده"),
    BLOCKED_BY_LOCK("Blocked by Emergency Lock", "مسدود با قفل اضطراری")
}

/**
 * Type of action an opportunity or agent can propose.
 */
enum class ActionType(val labelEn: String, val labelFa: String) {
    SCHEDULE_FOCUS_BLOCK("Schedule Focus Block", "زمان‌بندی تمرکز"),
    REPLAN_MISSION("Replan Mission Tasks", "بازطراحی وظایف مأموریت"),
    NOTIFY_CRITICAL_DEADLINE("Notify Critical Deadline", "هشدار مهلت بحرانی"),
    AUTOMATE_WORKFLOW("Automate Routine Task", "خودکارسازی کار روتین"),
    SYNC_CROSS_DEVICE("Sync Device State", "همگام‌سازی بین‌دستگاهی"),
    RESTRICT_SYSTEM_ACCESS("Restrict Privileged Access", "محدودسازی دسترسی ویژه")
}

/**
 * Structured action proposal within AWARE.
 */
data class ProposedAction(
    val actionType: ActionType,
    val targetPayload: String,
    val requiredPermission: String,
    val executionSummary: String
)

/**
 * Live snapshot of current context evaluated by AWARE.
 */
data class ContextSnapshot(
    val timestamp: Long = System.currentTimeMillis(),
    val focusWindow: String, // e.g., "Deep Work (09:00 - 11:30)"
    val currentActivity: String,
    val cognitiveLoad: String, // "Optimal", "High", "Fatigue Risk"
    val activeMissionsCount: Int,
    val blockedTasksCount: Int,
    val networkStatus: String, // "Online - Secure Gateway", "Offline Local Safe Mode"
    val emergencyLockActive: Boolean = false
)

/**
 * Detected behavior or environmental pattern.
 */
data class PatternDetection(
    val id: String,
    val title: String,
    val description: String,
    val occurrences: Int,
    val confidence: Float,
    val detectedAt: Long = System.currentTimeMillis()
)

/**
 * Proactive opportunity generated by AWARE engine.
 */
data class AwareOpportunity(
    val id: String,
    val title: String,
    val description: String,
    val triggerReason: String,
    val proposedAction: ProposedAction,
    val riskLevel: RiskLevel,
    val status: OpportunityStatus = OpportunityStatus.PENDING,
    val createdAt: Long = System.currentTimeMillis(),
    val executedAt: Long? = null
)

/**
 * Types of user activities tracked by AWARE pattern listener.
 */
enum class ActivityEventType(val labelEn: String, val labelFa: String) {
    TASK_INTERACTION("Task Interaction", "تعامل با وظیفه"),
    FOCUS_SESSION_START("Focus Session Start", "شروع جلسه تمرکز"),
    FOCUS_SESSION_END("Focus Session End", "پایان جلسه تمرکز"),
    MISSION_BLOCKED("Mission Blocked Encounter", "مواجهه با مانع مأموریت"),
    HIGH_COGNITIVE_EFFORT("High Cognitive Effort", "تلاش شناختی بالا"),
    IDLE_STALL("Workstream Idle Stall", "سکون در جریان کاری"),
    LATE_NIGHT_WORK("Late Night Work Session", "فعالیت در ساعات پایانی شب"),
    DEVICE_BATTERY_DROP("Battery Level Degradation", "افت سطح شارژ باتری")
}

/**
 * Event representing user activity or behavioral interaction.
 */
data class UserActivityEvent(
    val id: String,
    val type: ActivityEventType,
    val category: String,
    val description: String,
    val timestamp: Long = System.currentTimeMillis(),
    val durationSeconds: Long = 0,
    val metadata: Map<String, String> = emptyMap()
)

/**
 * Real-time hardware and operating system state monitored by AWARE.
 */
data class SystemState(
    val batteryLevel: Int = 100,
    val isCharging: Boolean = false,
    val networkType: String = "WIFI",
    val isScreenInteractive: Boolean = true,
    val thermalThrottling: Boolean = false,
    val focusWindowActive: Boolean = false,
    val activeMissionsCount: Int = 0,
    val blockedTasksCount: Int = 0,
    val emergencyLockActive: Boolean = false,
    val timestamp: Long = System.currentTimeMillis()
)

/**
 * Result of zero-trust permission verification for proactive intervention suggestions.
 */
sealed class InterventionPermissionResult {
    data class Allowed(
        val requiredPermission: String,
        val evaluatedRisk: RiskLevel,
        val rationale: String
    ) : InterventionPermissionResult()

    data class RequiresOwnerConsent(
        val requiredPermission: String,
        val riskLevel: RiskLevel,
        val message: String
    ) : InterventionPermissionResult()

    data class BlockedByEmergencyLock(
        val reason: String
    ) : InterventionPermissionResult()

    data class PermissionDenied(
        val missingPermission: String,
        val reason: String
    ) : InterventionPermissionResult()
}

/**
 * Outcome of attempting to execute an intervention suggestion.
 */
sealed class InterventionExecutionResult {
    data class Success(val opportunityId: String, val auditDigest: String) : InterventionExecutionResult()
    data class ConsentNeeded(
        val opportunity: AwareOpportunity,
        val permissionResult: InterventionPermissionResult.RequiresOwnerConsent
    ) : InterventionExecutionResult()
    data class Blocked(val reason: String) : InterventionExecutionResult()
    data class Failed(val error: String) : InterventionExecutionResult()
}
