package com.example.sayvis.screentranslate

/**
 * Offline English → Persian glossary for on-screen text.
 *
 * Why a hand-written dictionary in a screen translator?
 *  - **Sovereignty:** the owner can leave `dictionaryOnly` on and every word on the screen
 *    is translated on the device, with nothing ever leaving it.
 *  - **Latency:** the overlay can repaint in the same frame, before any model call returns.
 *  - **Determinism:** interface verbs ("Save", "Cancel", "Delete") are short, ambiguous and
 *    extremely common; a reviewed translation beats a sampled one.
 *
 * The AI translator is still the tier that handles real prose ("Your subscription renews on
 * March 3rd and your card will be charged"), but everything the dictionary knows is free and
 * instant. [ScreenTranslationEngine] always tries the dictionary first.
 */
object ScreenLexicon {

    /** True when the lexicon can render [text] on its own, without any network call. */
    fun canTranslate(text: String): Boolean = lookup(text) != null

    /** Number of reviewed entries, shown to the owner in the interface. */
    val size: Int get() = PHRASES.size + WORDS.size

    /**
     * Exact phrase or word lookup. [text] is normalised first, so casing, trailing
     * punctuation and stretched whitespace from OCR do not defeat the match.
     */
    fun lookup(text: String): String? {
        val key = normalize(text)
        if (key.isEmpty()) return null
        PHRASES[key]?.let { return it }
        WORDS[key]?.let { return it }
        // "Save file" / "save_file" / "Save-file" → single-token glosses.
        val squeezed = key.replace(' ', '_')
        PHRASES[squeezed]?.let { return it }
        return null
    }

    /** Gloss of one token, including the plural / possessive fallbacks. */
    fun glossToken(token: String): String? {
        val key = normalize(token)
        if (key.isEmpty()) return null
        WORDS[key]?.let { return it }
        PHRASES[key]?.let { return it }
        if (key.endsWith("'s")) WORDS[key.removeSuffix("'s")]?.let { return it }
        if (key.endsWith("s") && key.length > 3) WORDS[key.removeSuffix("s")]?.let { return it }
        if (key.endsWith("es") && key.length > 4) WORDS[key.removeSuffix("es")]?.let { return it }
        return null
    }

    /**
     * Word-by-word composition for a line the phrase table does not know.
     *
     * Returns null when too much of the line would stay English — a half-Persian,
     * half-English sentence is worse than no overlay at all, and the engine should then
     * wait for the AI tier instead.
     */
    fun glossLine(text: String, minimumCoverage: Float = 0.6f): String? {
        val tokens = normalize(text).split(' ').filter { it.isNotEmpty() }
        if (tokens.isEmpty()) return null
        val rendered = StringBuilder()
        var translated = 0
        var considered = 0
        for (token in tokens) {
            val glossable = token.any { it.isLetter() }
            if (!glossable) {
                rendered.append(token).append(' ')
                continue
            }
            considered++
            val gloss = glossToken(token)
            if (gloss != null) {
                translated++
                rendered.append(gloss)
            } else {
                rendered.append(token)
            }
            rendered.append(' ')
        }
        if (considered == 0) return null
        val coverage = translated.toFloat() / considered.toFloat()
        if (coverage < minimumCoverage) return null
        return rendered.toString().trim()
    }

    /** Share of letter-bearing tokens the lexicon knows — used for live statistics. */
    fun coverage(text: String): Float {
        val tokens = normalize(text).split(' ').filter { token -> token.any { it.isLetter() } }
        if (tokens.isEmpty()) return 0f
        return tokens.count { glossToken(it) != null }.toFloat() / tokens.size
    }

    /** Lower-cased, whitespace-collapsed, punctuation-stripped lookup key. */
    fun normalize(raw: String): String {
        val builder = StringBuilder(raw.length)
        for (ch in raw) {
            when {
                ch == '\u2019' || ch == '`' -> builder.append('\'')
                ch.isLetterOrDigit() || ch == '\'' || ch == '-' || ch == '_' || ch == '/' || ch == '.' ->
                    builder.append(ch.lowercaseChar())
                ch.isWhitespace() -> builder.append(' ')
                else -> builder.append(' ')
            }
        }
        return builder.toString()
            .replace(Regex("\\s+"), " ")
            .trim()
            .trim('.', ',', ':', ';', '!', '?', '"', '\'', '-', '/', '_')
    }

    // ------------------------------------------------------------------ phrases

    private val PHRASES: Map<String, String> = buildMap {
        // ---- sign in / account ----
        put("sign in", "ورود")
        put("sign out", "خروج از حساب")
        put("log in", "ورود")
        put("log out", "خروج")
        put("sign up", "ثبت‌نام")
        put("sign in to continue", "برای ادامه وارد شوید")
        put("create account", "ساخت حساب")
        put("forgot password", "رمز عبور را فراموش کرده‌اید؟")
        put("forgot your password", "رمز عبور خود را فراموش کرده‌اید؟")
        put("reset password", "بازنشانی رمز عبور")
        put("change password", "تغییر رمز عبور")
        put("current password", "رمز عبور فعلی")
        put("new password", "رمز عبور جدید")
        put("confirm password", "تکرار رمز عبور")
        put("remember me", "مرا به خاطر بسپار")
        put("keep me signed in", "من را واردشده نگه دار")
        put("enter your email", "ایمیل خود را وارد کنید")
        put("email address", "نشانی ایمیل")
        put("phone number", "شمارهٔ تلفن")
        put("user name", "نام کاربری")
        put("username", "نام کاربری")
        put("account settings", "تنظیمات حساب")
        put("my account", "حساب من")
        put("verify your email", "ایمیل خود را تأیید کنید")
        put("verification code", "کد تأیید")
        put("confirmation code", "کد تأیید")
        put("two factor authentication", "احراز هویت دو مرحله‌ای")
        put("password must be at least", "رمز عبور باید دست‌کم")
        put("incorrect password", "رمز عبور نادرست است")
        put("wrong password", "رمز عبور اشتباه است")
        put("loading your account", "در حال بارگذاری حساب شما")

        // ---- onboarding / dialogs ----
        put("welcome", "خوش آمدید")
        put("get started", "شروع کنید")
        put("learn more", "بیشتر بدانید")
        put("are you sure", "مطمئن هستید؟")
        put("are you sure you want to delete", "آیا از حذف مطمئن هستید؟")
        put("delete permanently", "برای همیشه حذف شود")
        put("this action cannot be undone", "این کار قابل بازگشت نیست")
        put("unsaved changes", "تغییرهای ذخیره‌نشده")
        put("discard changes", "لغو تغییرها")
        put("save changes", "ذخیرهٔ تغییرها")
        put("save and exit", "ذخیره و خروج")
        put("do not ask again", "دیگر نپرس")
        put("allow all", "اجازه به همه")
        put("not now", "اکنون نه")
        put("maybe later", "شاید بعداً")
        put("try again", "دوباره تلاش کنید")
        put("please wait", "لطفاً صبر کنید")
        put("please try again later", "لطفاً بعداً دوباره تلاش کنید")
        put("something went wrong", "خطایی رخ داد")
        put("an error occurred", "خطایی رخ داد")
        put("no internet connection", "اتصال اینترنت برقرار نیست")
        put("check your connection", "اتصال خود را بررسی کنید")
        put("connection lost", "ارتباط قطع شد")
        put("connection restored", "ارتباط برقرار شد")

        // ---- navigation ----
        put("go back", "بازگشت")
        put("back to", "بازگشت به")
        put("next page", "صفحهٔ بعد")
        put("previous page", "صفحهٔ قبل")
        put("skip this step", "رد کردن این مرحله")
        put("continue", "ادامه")
        put("see all", "مشاهدهٔ همه")
        put("show more", "نمایش بیشتر")
        put("show less", "نمایش کمتر")
        put("load more", "بارگذاری بیشتر")
        put("pull to refresh", "برای تازه‌سازی بکشید")
        put("swipe to delete", "برای حذف بکشید")
        put("search here", "اینجا جست‌وجو کنید")
        put("search history", "تاریخچهٔ جست‌وجو")
        put("no results", "نتیجه‌ای یافت نشد")
        put("no results found", "نتیجه‌ای یافت نشد")
        put("no items", "موردی وجود ندارد")
        put("nothing here yet", "هنوز چیزی اینجا نیست")
        put("end of list", "پایان فهرست")
        put("select all", "انتخاب همه")
        put("deselect all", "لغو انتخاب همه")

        // ---- settings & system ----
        put("settings", "تنظیمات")
        put("advanced settings", "تنظیمات پیشرفته")
        put("general settings", "تنظیمات عمومی")
        put("app settings", "تنظیمات برنامه")
        put("dark mode", "حالت تیره")
        put("light mode", "حالت روشن")
        put("system default", "پیش‌فرض سیستم")
        put("do not disturb", "مزاحم نشوید")
        put("airplane mode", "حالت هواپیما")
        put("mobile data", "دادهٔ همراه")
        put("wi fi", "وای‌فای")
        put("wi-fi", "وای‌فای")
        put("bluetooth", "بلوتوث")
        put("hotspot", "نقطهٔ اتصال")
        put("screen brightness", "روشنایی صفحه")
        put("screen timeout", "زمان خاموشی صفحه")
        put("auto rotate", "چرخش خودکار")
        put("font size", "اندازهٔ قلم")
        put("font style", "سبک قلم")
        put("display size", "اندازهٔ نمایش")
        put("storage", "فضای ذخیره‌سازی")
        put("internal storage", "حافظهٔ داخلی")
        put("free up space", "آزادسازی فضا")
        put("battery saver", "بهینه‌ساز باتری")
        put("power saving mode", "حالت ذخیرهٔ انرژی")
        put("data saver", "کاهش مصرف داده")
        put("location services", "خدمات موقعیت مکانی")
        put("app permissions", "مجوزهای برنامه")
        put("privacy policy", "سیاست حریم خصوصی")
        put("terms of service", "شرایط استفاده")
        put("terms and conditions", "شرایط و ضوابط")
        put("cookie settings", "تنظیمات کوکی")
        put("clear cache", "پاک کردن حافظهٔ نهان")
        put("clear data", "پاک کردن داده‌ها")
        put("uninstall app", "حذف برنامه")
        put("app info", "اطلاعات برنامه")
        put("about this app", "دربارهٔ این برنامه")
        put("version", "نسخه")
        put("build number", "شمارهٔ ساخت")
        put("developer options", "گزینه‌های توسعه‌دهنده")
        put("system update", "به‌روزرسانی سیستم")
        put("update available", "به‌روزرسانی موجود است")
        put("update now", "اکنون به‌روزرسانی کن")
        put("install now", "اکنون نصب کن")
        put("check for updates", "بررسی به‌روزرسانی")
        put("what's new", "تازه‌ها")
        put("release notes", "یادداشت انتشار")
        put("permissions required", "مجوزهای لازم")
        put("grant permission", "اعطای مجوز")
        put("allow access", "اجازهٔ دسترسی")
        put("deny", "رد کردن")
        put("always allow", "همیشه اجازه بده")
        put("only this time", "فقط این بار")
        put("while using the app", "در حین استفاده از برنامه")

        // ---- e-mail clients ----
        put("inbox", "صندوق ورودی")
        put("sent items", "فرستاده‌شده‌ها")
        put("drafts", "پیش‌نویس‌ها")
        put("trash", "زباله‌دان")
        put("spam", "هرزنامه")
        put("archive", "بایگانی")
        put("mark as read", "علامت‌گذاری به‌عنوان خوانده‌شده")
        put("mark as unread", "علامت‌گذاری به‌عنوان خوانده‌نشده")
        put("reply all", "پاسخ به همه")
        put("forward", "بازفرست")
        put("compose", "نامهٔ تازه")
        put("new message", "پیام تازه")
        put("attachments", "پیوست‌ها")
        put("no subject", "بدون موضوع")
        put("to", "گیرنده")
        put("subject", "موضوع")
        put("send", "ارسال")
        put("message sent", "پیام فرستاده شد")

        // ---- media & social ----
        put("now playing", "در حال پخش")
        put("play next", "پخش بعدی")
        put("add to queue", "افزودن به صف پخش")
        put("add to playlist", "افزودن به سیاهه‌پخش")
        put("add to favourites", "افزودن به برگزیده‌ها")
        put("shuffle", "پخش تصادفی")
        put("repeat", "تکرار")
        put("skip ad", "رد کردن آگهی")
        put("watch later", "تماشا در فرصتی دیگر")
        put("subscribe", "عضویت")
        put("unsubscribe", "لغو عضویت")
        put("subscribed", "عضو شده‌اید")
        put("follow", "دنبال کردن")
        put("following", "دنبال‌شده")
        put("unfollow", "لغو دنبال کردن")
        put("share", "هم‌رسانی")
        put("copy link", "رونوشت پیوند")
        put("report", "گزارش")
        put("block user", "مسدود کردن کاربر")
        put("write a comment", "نوشتن دیدگاه")
        put("add a comment", "افزودن دیدگاه")
        put("view all comments", "مشاهدهٔ همهٔ دیدگاه‌ها")
        put("likes", "پسندها")
        put("views", "بازدیدها")
        put("share this post", "هم‌رسانی این نوشته")
        put("create new post", "ساخت نوشتهٔ تازه")
        put("go live", "پخش زنده")
        put("live now", "اکنون زنده")

        // ---- shopping & payments ----
        put("add to cart", "افزودن به سبد خرید")
        put("view cart", "مشاهدهٔ سبد خرید")
        put("proceed to checkout", "ادامهٔ فرایند خرید")
        put("continue shopping", "ادامهٔ خرید")
        put("order summary", "خلاصهٔ سفارش")
        put("payment method", "روش پرداخت")
        put("credit card", "کارت اعتباری")
        put("debit card", "کارت نقدی")
        put("cash on delivery", "پرداخت در محل")
        put("card number", "شمارهٔ کارت")
        put("expiry date", "تاریخ انقضا")
        put("security code", "کد امنیتی")
        put("billing address", "نشانی صورت‌حساب")
        put("shipping address", "نشانی ارسال")
        put("free shipping", "ارسال رایگان")
        put("delivery time", "زمان تحویل")
        put("estimated delivery", "زمان تقریبی تحویل")
        put("track order", "پیگیری سفارش")
        put("order placed", "سفارش ثبت شد")
        put("order number", "شمارهٔ سفارش")
        put("out of stock", "ناموجود")
        put("in stock", "موجود")
        put("sold out", "تمام شد")
        put("add to wishlist", "افزودن به فهرست آرزو")
        put("apply coupon", "اعمال کد تخفیف")
        put("coupon code", "کد تخفیف")
        put("limited time offer", "پیشنهاد زمان محدود")
        put("best seller", "پرفروش‌ترین")
        put("customer reviews", "دیدگاه مشتریان")
        put("write a review", "نوشتن دیدگاه")
        put("buy now", "اکنون بخر")
        put("place order", "ثبت سفارش")
        put("cancel order", "لغو سفارش")
        put("refund requested", "درخواست بازپرداخت")
        put("money back guarantee", "تضمین بازگشت پول")
        put("price", "قیمت")
        put("total price", "قیمت کل")
        put("subtotal", "جمع جزء")
        put("discount", "تخفیف")
        put("tax", "مالیات")
        put("shipping", "هزینهٔ ارسال")
        put("grand total", "جمع نهایی")

        // ---- travel ----
        put("book now", "اکنون رزرو کن")
        put("check in", "ورود")
        put("check out", "خروج")
        put("one way", "یک‌طرفه")
        put("round trip", "رفت و برگشت")
        put("departure time", "زمان پرواز")
        put("arrival time", "زمان رسیدن")
        put("boarding pass", "کارت پرواز")
        put("flight status", "وضعیت پرواز")
        put("delayed", "با تأخیر")
        put("cancelled", "لغو شده")
        put("on time", "به‌موقع")
        put("gate number", "شمارهٔ دروازه")
        put("seat number", "شمارهٔ صندلی")
        put("baggage claim", "تحویل بار")
        put("passport number", "شمارهٔ گذرنامه")
        put("reservation confirmed", "رزرو تأیید شد")
        put("table for two", "میز برای دو نفر")
        put("opening hours", "ساعت کار")
        put("open now", "اکنون باز است")
        put("closed", "بسته")
        put("free entry", "ورود آزاد")
        put("directions", "مسیر")
        put("nearby", "نزدیک")
        put("distance", "فاصله")
        put("estimated time", "زمان تقریبی")

        // ---- work & productivity ----
        put("new document", "سند تازه")
        put("open file", "باز کردن پرونده")
        put("recent files", "پرونده‌های اخیر")
        put("save as", "ذخیره با نام")
        put("download as pdf", "دانلود به‌صورت PDF")
        put("print preview", "پیش‌نمایش چاپ")
        put("page setup", "تنظیمات صفحه")
        put("word count", "شمارش واژه")
        put("spell check", "غلط‌یابی")
        put("track changes", "پیگیری تغییرها")
        put("share document", "هم‌رسانی سند")
        put("add comment", "افزودن یادداشت")
        put("due date", "مهلت انجام")
        put("assign to", "واگذاری به")
        put("mark as complete", "علامت‌گذاری به‌عنوان انجام‌شده")
        put("in progress", "در حال انجام")
        put("not started", "شروع‌نشده")
        put("priority", "اولویت")
        put("high priority", "اولویت بالا")
        put("low priority", "اولویت پایین")
        put("time tracking", "ثبت زمان کار")
        put("team members", "اعضای تیم")
        put("meeting notes", "یادداشت جلسه")
        put("schedule meeting", "زمان‌بندی جلسه")
        put("join meeting", "پیوستن به جلسه")
        put("leave meeting", "ترک جلسه")
        put("mute microphone", "بی‌صدا کردن میکروفون")
        put("turn off camera", "خاموش کردن دوربین")
        put("share screen", "هم‌رسانی صفحه")
        put("end call", "پایان تماس")
        put("answer call", "پاسخ به تماس")
        put("decline", "رد تماس")

        // ---- errors & states ----
        put("loading", "در حال بارگذاری")
        put("loading please wait", "در حال بارگذاری، لطفاً صبر کنید")
        put("refreshing", "در حال تازه‌سازی")
        put("processing", "در حال پردازش")
        put("uploading", "در حال بارگذاری روی سرور")
        put("downloading", "در حال دانلود")
        put("connecting", "در حال اتصال")
        put("reconnecting", "در حال اتصال دوباره")
        put("request failed", "درخواست ناموفق بود")
        put("network error", "خطای شبکه")
        put("server error", "خطای سرور")
        put("internal server error", "خطای داخلی سرور")
        put("service unavailable", "سرویس در دسترس نیست")
        put("not found", "یافت نشد")
        put("page not found", "صفحه یافت نشد")
        put("access denied", "دسترسی رد شد")
        put("permission denied", "مجوز رد شد")
        put("unauthorized", "دسترسی غیرمجاز")
        put("session expired", "نشست منقضی شد")
        put("timeout", "پایان مهلت")
        put("try again later", "بعداً دوباره تلاش کنید")
        put("something went wrong please try again", "خطایی رخ داد؛ لطفاً دوباره تلاش کنید")
        put("no connection", "اتصال برقرار نیست")
        put("offline mode", "حالت آفلاین")
        put("synchronising", "در حال همگام‌سازی")
        put("last updated", "آخرین به‌روزرسانی")
        put("updated", "به‌روزرسانی شد")
        put("saved", "ذخیره شد")
        put("deleted", "حذف شد")
        put("copied", "رونوشت شد")
        put("success", "موفق")
        put("failed", "ناموفق")
        put("completed", "تکمیل‌شده")
        put("cancelled by user", "توسط کاربر لغو شد")
        put("pending", "در انتظار")
        put("warning", "هشدار")
        put("error", "خطا")
        put("attention", "توجه")
        put("required", "الزامی")
        put("optional", "اختیاری")
        put("recommended", "پیشنهادی")
        put("enabled", "فعال")
        put("disabled", "غیرفعال")
        put("on", "روشن")
        put("off", "خاموش")
        put("yes", "بله")
        put("no", "خیر")
        put("ok", "تأیید")
        put("okay", "تأیید")
        put("cancel", "لغو")
        put("close", "بستن")
        put("delete", "حذف")
        put("edit", "ویرایش")
        put("done", "انجام شد")
        put("apply", "اعمال")
        put("remove", "برداشتن")
        put("undo", "واگرد")
        put("redo", "ازنو")
        put("retry", "تلاش دوباره")
        put("skip", "رد کردن")
        put("finish", "پایان")
        put("exit", "خروج")
        put("quit", "بستن برنامه")
        put("confirm", "تأیید")
        put("submit", "ارسال")
        put("accept", "پذیرفتن")
        put("reject", "رد کردن")
        put("dismiss", "بی‌اعتنا شدن")
        put("refresh", "تازه‌سازی")
        put("reload", "بارگذاری دوباره")
        put("restart", "راه‌اندازی دوباره")
        put("reset", "بازنشانی")
        put("restore", "بازیابی")
        put("backup", "پشتیبان‌گیری")
        put("sync now", "اکنون همگام‌سازی کن")
        put("install", "نصب")
        put("uninstall", "حذف نصب")
        put("upgrade", "ارتقا")
        put("downgrade", "تنزل")
        put("sign", "امضا")
        put("scroll down", "به پایین بروید")
        put("scroll up", "به بالا بروید")
        put("zoom in", "بزرگ‌نمایی")
        put("zoom out", "کوچک‌نمایی")
        put("move", "جابه‌جایی")
        put("rename", "تغییر نام")
        put("duplicate", "تکثیر")
        put("export", "خروجی گرفتن")
        put("import", "ورود داده")
        put("print", "چاپ")
        put("scan", "اسکن")
        put("record", "ضبط")
        put("start recording", "شروع ضبط")
        put("stop recording", "پایان ضبط")

        // ---- time & calendar ----
        put("today", "امروز")
        put("tomorrow", "فردا")
        put("yesterday", "دیروز")
        put("this week", "این هفته")
        put("this month", "این ماه")
        put("this year", "امسال")
        put("last week", "هفتهٔ گذشته")
        put("next week", "هفتهٔ آینده")
        put("all day", "تمام روز")
        put("all events", "همهٔ رویدادها")
        put("new event", "رویداد تازه")
        put("add reminder", "افزودن یادآور")
        put("set alarm", "تنظیم زنگ هشدار")
        put("snooze", "تعویق")
        put("reminder", "یادآور")
        put("repeat weekly", "تکرار هفتگی")
        put("repeat daily", "تکرار روزانه")
        put("start time", "زمان شروع")
        put("end time", "زمان پایان")
        put("add to calendar", "افزودن به تقویم")
        put("participants", "شرکت‌کنندگان")
        put("location", "مکان")
        put("description", "توضیح")
        put("notes", "یادداشت‌ها")
        put("attendees", "حاضران")

        // ---- weather ----
        put("feels like", "دمای محسوس")
        put("chance of rain", "احتمال بارش")
        put("sunrise", "طلوع")
        put("sunset", "غروب")
        put("wind speed", "سرعت باد")
        put("air quality", "کیفیت هوا")
        put("seven day forecast", "پیش‌بینی هفت‌روزه")
        put("hourly forecast", "پیش‌بینی ساعتی")
        put("severe weather alert", "هشدار وضعیت جوی شدید")
    }

    // -------------------------------------------------------------------- words

    private val WORDS: Map<String, String> = buildMap {
        // verbs & actions
        put("open", "باز کردن")
        put("close", "بستن")
        put("save", "ذخیره")
        put("saved", "ذخیره‌شده")
        put("cancel", "لغو")
        put("delete", "حذف")
        put("remove", "برداشتن")
        put("edit", "ویرایش")
        put("add", "افزودن")
        put("create", "ساختن")
        put("new", "تازه")
        put("update", "به‌روزرسانی")
        put("rename", "تغییر نام")
        put("move", "جابه‌جایی")
        put("copy", "رونوشت")
        put("paste", "چسباندن")
        put("cut", "برش")
        put("undo", "واگرد")
        put("redo", "ازنو")
        put("search", "جست‌وجو")
        put("find", "یافتن")
        put("replace", "جایگزینی")
        put("select", "انتخاب")
        put("choose", "انتخاب کردن")
        put("set", "تنظیم کردن")
        put("change", "تغییر دادن")
        put("enable", "فعال کردن")
        put("disable", "غیرفعال کردن")
        put("allow", "اجازه دادن")
        put("block", "مسدود کردن")
        put("confirm", "تأیید کردن")
        put("verify", "تأیید کردن")
        put("send", "ارسال")
        put("receive", "دریافت")
        put("download", "دانلود")
        put("upload", "بارگذاری")
        put("install", "نصب کردن")
        put("uninstall", "حذف کردن")
        put("connect", "اتصال")
        put("disconnect", "قطع اتصال")
        put("login", "ورود")
        put("logout", "خروج")
        put("subscribe", "عضویت")
        put("share", "هم‌رسانی")
        put("print", "چاپ کردن")
        put("export", "خروجی")
        put("import", "ورودی")
        put("refresh", "تازه‌سازی")
        put("reset", "بازنشانی")
        put("restore", "بازیابی")
        put("view", "نمایش")
        put("preview", "پیش‌نمایش")
        put("continue", "ادامه")
        put("start", "شروع")
        put("stop", "توقف")
        put("pause", "مکث")
        put("resume", "ادامه")
        put("play", "پخش")
        put("record", "ضبط")
        put("mute", "بی‌صدا")
        put("unmute", "باصدا")
        put("repeat", "تکرار")
        put("dismiss", "رد کردن")
        put("try", "تلاش کردن")
        put("retry", "تلاش دوباره")
        put("help", "کمک")
        put("support", "پشتیبانی")
        put("contact", "تماس")
        put("report", "گزارش")
        put("sync", "همگام‌سازی")
        put("lock", "قفل کردن")
        put("unlock", "باز کردن قفل")
        put("sign", "امضا کردن")
        put("scan", "اسکن کردن")
        put("zoom", "بزرگ‌نمایی")
        put("scroll", "پیمایش")
        put("drag", "کشیدن")
        put("drop", "رها کردن")
        put("tap", "لمس")
        put("press", "فشردن")
        put("hold", "نگه داشتن")
        put("swipe", "کشیدن انگشت")
        put("pinch", "باز و بسته کردن دو انگشت")
        put("enter", "وارد کردن")
        put("exit", "خروج")
        put("buy", "خرید")
        put("sell", "فروش")
        put("pay", "پرداخت")
        put("book", "رزرو")
        put("order", "سفارش")
        put("track", "پیگیری")
        put("rate", "امتیاز دادن")
        put("review", "بررسی")
        put("comment", "دیدگاه")
        put("follow", "دنبال کردن")
        put("like", "پسندیدن")
        put("commenting", "دیدگاه‌نویسی")
        put("translate", "ترجمه")
        put("speak", "صحبت کردن")
        put("listen", "گوش دادن")

        // interface nouns
        put("screen", "صفحه")
        put("display", "نمایشگر")
        put("window", "پنجره")
        put("tab", "زبانه")
        put("page", "صفحه")
        put("menu", "فهرست")
        put("button", "دکمه")
        put("icon", "نماد")
        put("item", "مورد")
        put("list", "فهرست")
        put("grid", "شبکه")
        put("card", "کارت")
        put("panel", "پنل")
        put("sidebar", "نوار کنار")
        put("toolbar", "نوار ابزار")
        put("keyboard", "صفحه‌کلید")
        put("mouse", "موشواره")
        put("pointer", "نشانگر")
        put("cursor", "مکان‌نما")
        put("dialog", "پنجرهٔ گفت‌وگو")
        put("notification", "اعلان")
        put("notifications", "اعلان‌ها")
        put("alert", "هشدار")
        put("message", "پیام")
        put("messages", "پیام‌ها")
        put("chat", "گفت‌وگو")
        put("email", "ایمیل")
        put("mail", "نامه")
        put("call", "تماس")
        put("phone", "تلفن")
        put("camera", "دوربین")
        put("photo", "عکس")
        put("image", "تصویر")
        put("video", "ویدیو")
        put("audio", "صدا")
        put("music", "موسیقی")
        put("file", "پرونده")
        put("files", "پرونده‌ها")
        put("folder", "پوشه")
        put("document", "سند")
        put("documents", "سندها")
        put("attachment", "پیوست")
        put("link", "پیوند")
        put("url", "نشانی")
        put("address", "نشانی")
        put("name", "نام")
        put("title", "عنوان")
        put("text", "متن")
        put("word", "واژه")
        put("words", "واژه‌ها")
        put("sentence", "جمله")
        put("paragraph", "بند")
        put("line", "خط")
        put("character", "نویسه")
        put("letter", "حرف")
        put("number", "شماره")
        put("count", "شمارش")
        put("size", "اندازه")
        put("width", "پهنا")
        put("height", "بلندی")
        put("weight", "وزن")
        put("color", "رنگ")
        put("colour", "رنگ")
        put("style", "سبک")
        put("theme", "پوسته")
        put("layout", "چیدمان")
        put("design", "طراحی")
        put("background", "پس‌زمینه")
        put("foreground", "پیش‌زمینه")
        put("border", "حاشیه")
        put("shadow", "سایه")
        put("opacity", "شفافیت")
        put("transparency", "شفافیت")
        put("position", "موقعیت")
        put("alignment", "ترازبندی")
        put("direction", "جهت")
        put("language", "زبان")
        put("english", "انگلیسی")
        put("persian", "فارسی")
        put("arabic", "عربی")
        put("translation", "ترجمه")
        put("dictionary", "واژه‌نامه")
        put("voice", "صدا")
        put("sound", "صدا")
        put("volume", "بلندی صدا")
        put("brightness", "روشنایی")
        put("timer", "زمان‌سنج")
        put("clock", "ساعت")
        put("calendar", "تقویم")
        put("time", "زمان")
        put("date", "تاریخ")
        put("day", "روز")
        put("week", "هفته")
        put("month", "ماه")
        put("year", "سال")
        put("hour", "ساعت")
        put("minute", "دقیقه")
        put("second", "ثانیه")
        put("morning", "صبح")
        put("noon", "ظهر")
        put("afternoon", "بعدازظهر")
        put("evening", "شب")
        put("night", "شب")
        put("today", "امروز")
        put("tomorrow", "فردا")
        put("yesterday", "دیروز")
        put("now", "اکنون")
        put("later", "بعداً")
        put("soon", "به‌زودی")
        put("always", "همیشه")
        put("never", "هرگز")
        put("sometimes", "گاهی")
        put("often", "اغلب")
        put("again", "دوباره")
        put("also", "همچنین")
        put("only", "فقط")
        put("all", "همه")
        put("none", "هیچ")
        put("some", "برخی")
        put("many", "بسیاری")
        put("few", "اندکی")
        put("more", "بیشتر")
        put("less", "کمتر")
        put("most", "بیشترین")
        put("least", "کمترین")
        put("each", "هر")
        put("every", "هر")
        put("other", "دیگر")
        put("another", "دیگری")
        put("same", "یکسان")
        put("different", "متفاوت")
        put("first", "نخستین")
        put("last", "آخرین")
        put("next", "بعدی")
        put("previous", "پیشین")
        put("current", "جاری")
        put("old", "قدیمی")
        put("older", "قدیمی‌تر")
        put("latest", "تازه‌ترین")
        put("recent", "اخیر")
        put("good", "خوب")
        put("better", "بهتر")
        put("best", "بهترین")
        put("bad", "بد")
        put("worse", "بدتر")
        put("worst", "بدترین")
        put("great", "عالی")
        put("nice", "خوب")
        put("important", "مهم")
        put("urgent", "فوری")
        put("available", "در دسترس")
        put("unavailable", "در دسترس نیست")
        put("ready", "آماده")
        put("busy", "مشغول")
        put("free", "آزاد")
        put("paid", "پرداخت‌شده")
        put("unpaid", "پرداخت‌نشده")
        put("free trial", "دورهٔ آزمایشی رایگان")
        put("trial", "دورهٔ آزمایشی")
        put("expired", "منقضی‌شده")
        put("expires", "منقضی می‌شود")
        put("active", "فعال")
        put("inactive", "غیرفعال")
        put("online", "آنلاین")
        put("offline", "آفلاین")
        put("connected", "متصل")
        put("disconnected", "قطع")
        put("loading", "در حال بارگذاری")
        put("waiting", "در انتظار")
        put("searching", "در حال جست‌وجو")
        put("working", "در حال کار")
        put("done", "انجام‌شده")
        put("finished", "پایان‌یافته")
        put("failed", "ناموفق")
        put("successful", "موفق")
        put("error", "خطا")
        put("errors", "خطاها")
        put("warning", "هشدار")
        put("problem", "مشکل")
        put("issue", "اشکال")
        put("bug", "اشکال نرم‌افزاری")
        put("fix", "رفع")
        put("fixed", "رفع شد")
        put("solution", "راهکار")
        put("version", "نسخه")
        put("upgrade", "ارتقا")
        put("feature", "قابلیت")
        put("features", "قابلیت‌ها")
        put("option", "گزینه")
        put("options", "گزینه‌ها")
        put("settings", "تنظیمات")
        put("preferences", "ترجیحات")
        put("profile", "نمایه")
        put("account", "حساب")
        put("accounts", "حساب‌ها")
        put("user", "کاربر")
        put("users", "کاربران")
        put("owner", "مالک")
        put("guest", "مهمان")
        put("admin", "مدیر")
        put("administrator", "مدیر سیستم")
        put("team", "تیم")
        put("group", "گروه")
        put("member", "عضو")
        put("members", "اعضا")
        put("contacts", "مخاطبان")
        put("friend", "دوست")
        put("friends", "دوستان")
        put("client", "مشتری")
        put("customer", "مشتری")
        put("provider", "سرویس‌دهنده")
        put("service", "سرویس")
        put("server", "سرور")
        put("network", "شبکه")
        put("internet", "اینترنت")
        put("connection", "اتصال")
        put("data", "داده")
        put("database", "پایگاه داده")
        put("storage", "حافظه")
        put("memory", "حافظه")
        put("space", "فضا")
        put("device", "دستگاه")
        put("devices", "دستگاه‌ها")
        put("mobile", "همراه")
        put("tablet", "رایانهٔ لوحی")
        put("computer", "رایانه")
        put("laptop", "رایانهٔ کیفی")
        put("desktop", "رومیزی")
        put("printer", "چاپگر")
        put("speaker", "بلندگو")
        put("headphones", "هدفون")
        put("microphone", "میکروفون")
        put("battery", "باتری")
        put("charging", "در حال شارژ")
        put("power", "توان")
        put("energy", "انرژی")
        put("wifi", "وای‌فای")
        put("bluetooth", "بلوتوث")
        put("signal", "سیگنال")
        put("password", "رمز عبور")
        put("passcode", "رمز عبور")
        put("pin", "رمز")
        put("username", "نام کاربری")
        put("token", "توکن")
        put("key", "کلید")
        put("security", "امنیت")
        put("privacy", "حریم خصوصی")
        put("permission", "مجوز")
        put("permissions", "مجوزها")
        put("access", "دسترسی")
        put("trust", "اعتماد")
        put("trusted", "مورد اعتماد")
        put("blocked", "مسدود")
        put("locked", "قفل‌شده")
        put("unlocked", "باز")
        put("safe", "ایمن")
        put("secure", "امن")
        put("risk", "ریسک")
        put("danger", "خطر")
        put("careful", "احتیاط")
        put("backup", "پشتیبان")
        put("encryption", "رمزنگاری")
        put("certificate", "گواهی")
        put("fingerprint", "اثر انگشت")
        put("biometric", "زیست‌سنجی")
        put("screen lock", "قفل صفحه")
        put("location", "موقعیت")
        put("camera access", "دسترسی دوربین")
        put("microphone access", "دسترسی میکروفون")
        put("notifications access", "دسترسی اعلان‌ها")
        put("screen access", "دسترسی به صفحه")

        // finance & trading
        put("money", "پول")
        put("price", "قیمت")
        put("cost", "هزینه")
        put("fee", "کارمزد")
        put("total", "جمع")
        put("balance", "موجودی")
        put("balance available", "موجودی قابل استفاده")
        put("credit", "اعتبار")
        put("debit", "بدهی")
        put("payment", "پرداخت")
        put("invoice", "صورت‌حساب")
        put("receipt", "رسید")
        put("refund", "بازپرداخت")
        put("tax", "مالیات")
        put("profit", "سود")
        put("loss", "زیان")
        put("market", "بازار")
        put("stock", "سهام")
        put("trade", "معامله")
        put("trading", "معامله‌گری")
        put("bid", "قیمت فروش")
        put("ask", "قیمت خرید")
        put("spread", "اختلاف قیمت")
        put("leverage", "اهرم")
        put("margin", "مارجین")
        put("portfolio", "سبد دارایی")
        put("investment", "سرمایه‌گذاری")
        put("interest", "بهره")
        put("exchange", "صرافی")
        put("currency", "ارز")
        put("dollar", "دلار")
        put("euro", "یورو")
        put("inflation", "تورم")
        put("revenue", "درآمد")
        put("budget", "بودجه")
        put("expense", "هزینه")
        put("savings", "پس‌انداز")
        put("loan", "وام")
        put("credit score", "امتیاز اعتباری")

        // descriptive words
        put("fast", "سریع")
        put("slow", "کند")
        put("easy", "آسان")
        put("hard", "سخت")
        put("simple", "ساده")
        put("complex", "پیچیده")
        put("private", "خصوصی")
        put("public", "عمومی")
        put("personal", "شخصی")
        put("shared", "هم‌رسانی‌شده")
        put("local", "محلی")
        put("remote", "دور")
        put("automatic", "خودکار")
        put("manual", "دستی")
        put("custom", "دلخواه")
        put("default", "پیش‌فرض")
        put("advanced", "پیشرفته")
        put("basic", "پایه")
        put("standard", "استاندارد")
        put("premium", "ویژه")
        put("upgrade to premium", "ارتقا به نسخهٔ ویژه")
        put("included", "شامل")
        put("excluded", "شامل نمی‌شود")
        put("required", "الزامی")
        put("optional", "اختیاری")
        put("recommended", "پیشنهادی")
        put("popular", "پرطرفدار")
        put("trending", "پرطرفدار")
        put("nearby", "نزدیک")
        put("far", "دور")
        put("closed", "بسته")
        put("empty", "خالی")
        put("full", "پر")
        put("left", "باقی‌مانده")
        put("remaining", "باقی‌مانده")
        put("unread", "خوانده‌نشده")
        put("updated", "به‌روز")
        put("verified", "تأییدشده")
        put("pending", "در انتظار")
        put("processing", "در حال پردازش")
        put("shipped", "ارسال‌شده")
        put("delivered", "تحویل‌شده")
        put("cancelled", "لغو‌شده")
        put("returned", "بازگردانده‌شده")

        // small function words (kept, because they appear alone in menus)
        put("and", "و")
        put("or", "یا")
        put("with", "با")
        put("without", "بدون")
        put("for", "برای")
        put("from", "از")
        put("to", "به")
        put("in", "در")
        put("on it", "روی آن")
        put("at", "در")
        put("please", "لطفاً")
        put("thank you", "سپاسگزارم")
        put("thanks", "ممنون")
        put("sorry", "متأسفم")
        put("hello", "سلام")
        put("hi", "سلام")
        put("goodbye", "خدانگهدار")
        put("welcome", "خوش آمدید")
        put("good morning", "صبح بخیر")
        put("good night", "شب بخیر")
        put("see you", "می‌بینمت")
        put("congratulations", "تبریک")
        put("good luck", "موفق باشید")
        put("well done", "آفرین")
        put("no problem", "مشکلی نیست")
        put("you are welcome", "خواهش می‌کنم")
        put("excuse me", "ببخشید")
        put("i don't know", "نمی‌دانم")
        put("i understand", "متوجه شدم")
        put("i don't understand", "متوجه نشدم")
        put("do you speak english", "انگلیسی صحبت می‌کنید؟")
        put("i speak a little persian", "کمی فارسی صحبت می‌کنم")
        put("how much is it", "چند است؟")
        put("where is it", "کجاست؟")
        put("what is this", "این چیست؟")
        put("what time is it", "ساعت چند است؟")
        put("help me", "کمکم کنید")
        put("call the police", "به پلیس زنگ بزنید")
        put("i need a doctor", "به پزشک نیاز دارم")
    }
}
